services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: consultacreditos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - internal
    restart: unless-stopped

  kafka:
    image: apache/kafka:3.7.0
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    networks:
      - internal
    restart: unless-stopped

  kafka-init:
    image: apache/kafka:3.7.0
    depends_on:
      kafka:
        condition: service_started
    entrypoint: ["/bin/sh", "-lc"]
    command:
      - >
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists
        --topic integrar-credito-constituido-entry --partitions 1 --replication-factor 1 &&
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists
        --topic consulta-creditos-audit --partitions 1 --replication-factor 1
    networks:
      - internal
    restart: "no"

  api:
    image: ghcr.io/oismaelash/consulta-creditos-dotnet-6-backend:${APP_VERSION}
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      Swagger__Enabled: "true"
      ConnectionStrings__Postgres: Host=postgres;Port=5432;Database=consultacreditos;Username=postgres;Password=${DB_PASSWORD}
      Kafka__BootstrapServers: kafka:9092
      Kafka__Topics__Integracao: integrar-credito-constituido-entry
      Kafka__Topics__Auditoria: consulta-creditos-audit
    depends_on:
      postgres:
        condition: service_started
      kafka:
        condition: service_started
    networks:
      - traefik
      - internal
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.consultacreditosapi.rule=Host(`${BASE_DOMAIN}`)${CUSTOM_DOMAIN:+ || Host(`${CUSTOM_DOMAIN}`)}
      - traefik.http.routers.consultacreditosapi.entrypoints=websecure
      - traefik.http.routers.consultacreditosapi.tls=true
      - traefik.http.routers.consultacreditosapi.tls.certresolver=letsencrypt
      - traefik.http.services.consultacreditosapi.loadbalancer.server.port=8080
    restart: unless-stopped

volumes:
  postgres_data_prod:

networks:
  traefik:
    external: true
  internal: